title: Insights
logo: /flower.JPG
email: ali [at] kazmi [dot] dev
blank_title: true
favicon: true
description: ""
show_downloads: false
remote_theme: BDHU/minimalist
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

sidebar:
  - name: Amazon
    link: https://www.amazon.com/dp/B0BWVP6J5S
  - name: Barnes and Noble
    link: https://www.barnesandnoble.com/s/Insights%20Ali%20kazmi
  - name: PDF
    link: /Insights.pdf

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]

cdn:
  jsdelivr:
    enabled: true
